# Generated by Django 5.0.2 on 2024-02-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('hospital', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
