# Generated by Django 5.0.2 on 2024-02-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourservice_delete_docters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
