# Generated by Django 5.0.2 on 2024-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ourservice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodavailabilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
