# Generated by Django 5.0.2 on 2024-02-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='booking',
        ),
    ]
