# Generated by Django 5.0.2 on 2024-02-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_medicine_patient_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='patient',
            new_name='name',
        ),
    ]
