# Generated by Django 5.0.2 on 2024-02-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_patient_prescription_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='name',
            new_name='patient',
        ),
        migrations.CreateModel(
            name='prescribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.prescription')),
            ],
        ),
    ]
