# Generated by Django 5.0.2 on 2024-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_name_prescription_patient_prescribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribed',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
