# Generated by Django 5.0.2 on 2024-02-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_prescribed_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescribed',
            old_name='prescription',
            new_name='Prescription',
        ),
    ]
