# Generated by Django 5.0.2 on 2024-02-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='appo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='deppp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.AddField(
            model_name='appo',
            name='depp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deppp'),
        ),
    ]
