# Generated by Django 5.0.2 on 2024-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ourdocters_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appo',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ourdocters',
            name='workingtime',
            field=models.DateTimeField(),
        ),
    ]
