# Generated by Django 5.0.2 on 2024-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_appo_date_alter_ourdocters_workingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docters_booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
