# Generated by Django 5.0.2 on 2024-02-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_ourdocters_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourdocters',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
